### ISSUE TITLE
Error: Unrecognized exam time: 6:30 PM

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#1005]
https://sentry.io/nusmods/v3/issues/524507037/

So, erm, how did these modules get an exam time of 6:30 PM? 

```
Error: Unrecognized exam time: 6:30 PM
  at getTimeSegment (./js/views/timetable/ExamCalendar.jsx:57:13)
  at None (./js/views/timetable/ExamCalendar.jsx:195:22)
  at Array.forEach (<anonymous>)
  at modulesWithExamDate (./js/views/timetable/ExamCalendar.jsx:183:30)
  at render (./js/views/timetable/ExamCalendar.jsx:216:35)
...
(11 additional frame(s) were not displayed)
```

**Comment by li-kai** [comment]
Are these impossible or an edge case we didn't expect?

**Comment by ZhangYiJiang** [comment]
Well, https://github.com/nusmodifications/nusmods/blob/master/scrapers/nus/gulp-tasks/local/consolidateForSem.js#L71 says that exam timing in the API output can only occur at 9am, 1pm, 2.30pm and 5pm (if I understand the code correctly)

**Comment by li-kai** [comment]
Ah, that's is correct for cors, but for examTimetable.js it can be any time...
