### ISSUE TITLE
Validate shared module codes before trying to fetch them 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#1175]
Some apps add additional query parameters. This is normally fine, except when you're sharing your timetable - these additional query params are being interpreted by the page as modules, which causes weird issues with loading. 

A good fix is to check if a module code is valid before dispatching fetch module action. We should also do something about fetch failures when the module bank is cold, but that can be for another time. 

https://sentry.io/nusmods/v3/issues/662845825/

```
Error: Request failed with status code 404
  at exports (../node_modules/axios/lib/core/createError.js:16:1)
  at settle (../node_modules/axios/lib/helpers/buildURL.js:3:1)
  at apply (../node_modules/axios/lib/adapters/xhr.js:77:1)
  at wrapped (../node_modules/raven-js/src/raven.js:377:1)
```

**Comment by abilash13** [comment]
I can work on this if that's okay?
