### ISSUE TITLE
Scraper fails when fetching Information Systems and Analytics modules initially

### ISSUE THREAD

**Issue by chrisgzf** [nusmodifications/nusmods#3323]
Same bug faced during the AY migration livestream. Tested on production scraper server.

```
04:09:10.708 ERROR scraper: PLC5019: Module description contains non-breaking spaces (semester=2, task=GetSemesterModules, year=2021/2022, moduleCode=PLC5019)
04:09:10.709 ERROR scraper: PLC5020: Module description contains non-breaking spaces (semester=2, task=GetSemesterModules, year=2021/2022, moduleCode=PLC5020)
04:09:45.328 ERROR scraper: CE5805A: Module description contains non-breaking spaces (semester=2, task=GetSemesterModules, year=2021/2022, moduleCode=CE5805A)
04:11:03.314 ERROR scraper: Cannot get modules from Information Systems and Analytics (semester=2, task=GetSemesterModules, year=2021/2022)
    UnknownApiError: <unknown>:190:57: not well-formed (invalid token)
        at mapErrorCode (/home/ubuntu/nusmods/scrapers/nus-v2/build/services/nus-api.js:41:21)
        at callApi (/home/ubuntu/nusmods/scrapers/nus-v2/build/services/nus-api.js:86:23)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
    --
    err.request: {
      "data": "{\"term\":\"2120\",\"acadorg\":\"00302ACAD1\"}",
      "url": "[REDACTED-SCRAPER-BASE-URL]"
    }
    --
    err.response: {
      "status": 200,
      "data": {
        "msg": "<unknown>:190:57: not well-formed (invalid token)",
        "code": "20000",
        "data": [],
        "ts": "20210708041103"
      }
    }
04:11:03.318 FATAL scraper: Fatal error
    TaskError: Cannot get module list
        at GetSemesterModules.run (/home/ubuntu/nusmods/scrapers/nus-v2/build/tasks/GetSemesterModules.js:61:19)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

To see this stack trace, `cat info-2021-07-08.04-06-14.log | yarn bunyan`.

The temporary workaround for this is:
![image](https://user-images.githubusercontent.com/4933577/124823833-37479200-dfa4-11eb-91fe-b4e66ed1e791.png)

But we should figure out what exactly is wrong

**Comment by chrisgzf** [comment]
Closing because we figured out the cause: One of Dept of ISA's modules had a non-standard character in the module description, and NUS's API couldn't return the data. This resulted in an entire sem2/st1/st2 worth of Dept of ISA's mods not being scraped.

This has since been resolved.
