### ISSUE TITLE
Unhandled rejection Error: [object Object] bluebird.js

### ISSUE THREAD

**Issue by Waffleboy** [nusmodifications/nusmods#420]
NUSMods has stopped working for me, the URL contains the module information but nothing appears.

![image](https://user-images.githubusercontent.com/12254813/28992780-59dec72e-79d8-11e7-8225-9f7e1374a9d8.png)

Tested on:
Samsung S6 Wifi + Network on chrome browser
Desktop Ubuntu 16 on chrome browser

Some errors appear in the console:

Full Traceback:
```

bluebird.js:953 Unhandled rejection Error: [object Object]
    at Object.ensureErrorObject (https://nusmods.com/app.js:53:2971)
    at n._rejectCallback (https://nusmods.com/app.js:52:4826)
    at o.__hardReject__.o._reject (https://nusmods.com/app.js:52:11635)
    at o._promiseRejected (https://nusmods.com/app.js:52:11956)
    at n._settlePromiseAt (https://nusmods.com/app.js:52:6775)
    at n._settlePromises (https://nusmods.com/app.js:52:8511)
    at i._drainQueue (https://nusmods.com/app.js:51:2660)
    at i._drainQueues (https://nusmods.com/app.js:51:2721)
    at drainQueues (https://nusmods.com/app.js:51:933)
d @ bluebird.js:953
n.formatAndLogError @ bluebird.js:661
n.fireRejectionEvent @ bluebird.js:716
n._notifyUnhandledRejection @ bluebird.js:1107
i._drainQueue @ bluebird.js:180
i._drainQueues @ bluebird.js:187
drainQueues @ bluebird.js:67
setTimeout (async)
l @ bluebird.js:131
i._queueTick @ bluebird.js:193
o @ bluebird.js:122
c.hasDevTools.i.settlePromises @ bluebird.js:157
n._queueSettlePromises @ bluebird.js:2817
n._fulfillUnchecked @ bluebird.js:2832
n._fulfill @ bluebird.js:2731
n._resolveCallback @ bluebird.js:2623
s @ bluebird.js:4247
(anonymous) @ jquery.js:3256
c @ jquery.js:3099
fireWith @ jquery.js:3211
n @ jquery.js:8264
(anonymous) @ jquery.js:8605
XMLHttpRequest.send (async)
send @ jquery.js:8630
ajax @ jquery.js:8166
ie.(anonymous function) @ jquery.js:8311
getJSON @ jquery.js:8294
getTimetable @ nusmods.js:52
onAdd @ TimetableModuleCollection.js:35
_ @ backbone.js:371
v @ backbone.js:356
h @ backbone.js:155
c.trigger @ backbone.js:346
_onModelEvent @ backbone.js:1155
_ @ backbone.js:372
v @ backbone.js:357
h @ backbone.js:155
c.trigger @ backbone.js:346
set @ backbone.js:913
add @ backbone.js:803
(anonymous) @ app.js:62
(anonymous) @ backbone.wreqr.js:108
request @ backbone.wreqr.js:260
request @ backbone.marionette.js:3114
(anonymous) @ app.js:159
M.map.M.collect @ underscore.js:172
(anonymous) @ app.js:158
Promise resolved (async)
(anonymous) @ app.js:143
M.map.M.collect @ underscore.js:172
(anonymous) @ app.js:140
_ @ backbone.js:369
v @ backbone.js:356
h @ backbone.js:155
c.trigger @ backbone.js:346
(anonymous) @ backbone.marionette.js:242
s.triggerMethod @ backbone.marionette.js:260
start @ backbone.marionette.js:3130
(anonymous) @ main.js:61
t @ bootstrap 07576bdf0e512ba154e1:19
(anonymous) @ bootstrap 07576bdf0e512ba154e1:39
(anonymous) @ bootstrap 07576bdf0e512ba154e1:39
jquery.min.js:2 Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://nusmods.com" from accessing a cross-origin frame.
    at contents (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:2:5154)
    at Function.map (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:14862)
    at ot.fn.init.ot.fn.(anonymous function) [as contents] (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:2:5271)
    at HTMLIFrameElement.eval (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/views/overlay/ActivityMonitorOverlayView.js:1:1894)
    at Function.each (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:14059)
    at ot.fn.init.each (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:11922)
    at e.bindActivityDetectors (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/views/overlay/ActivityMonitorOverlayView.js:1:1853)
    at e.init (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/ActivityMonitorController.js:1:255)
    at onLoaded (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/content.js:1:979)
    at eval (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/ComponentFactory.js:1:943)
```

**Comment by yangshun** [comment]
Thanks Thiru, we'll look into it immediately.

**Comment by yangshun** [comment]
The issue has been temporarily resolved. We'll look into the cause.
