### ISSUE TITLE
ReferenceError: localStorage is not defined

### ISSUE THREAD

**Issue by li-kai** [nusmodifications/nusmods#480]
https://sentry.io/share/issue/5b2abcb6db4047b7a670a7f152c483e0/

```
ReferenceError: localStorage is not defined
  at getItem (./js/storage/index.js:19:5)
  at loadState (./js/storage/index.js:44:12)
  at Object.266 (./js/main.js:14:32)
  at __webpack_require__ (/:1:119)
  at Object.265 (app.0db6babbb66a82a6b4d3.js:1241:18)
...
(12 additional frame(s) were not displayed)
```

**Comment by yangshun** [comment]
The recommended way to fix this is to use an in-memory version of localStorage instead. Refer to this [TODO](https://github.com/nusmodifications/nusmods/blob/master/v3/src/js/storage/index.js#L5)
