### ISSUE TITLE
React crashing on module finder page with NotFoundError 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#720]
Sentry report: https://sentry.io/nusmods/v3/issues/433349104/

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  at next (./js/middlewares/requests-middleware.js:23:12)
  at apply (./js/views/components/SearchBox.jsx:67:16)
...
(19 additional frame(s) were not displayed)
```

I suspect there's something to do with the async rendering shenanigans we're doing, which is interfering with React's virtual DOM reconciliation. Unfortunately reproducing this may be really difficult. Still, it's a hard crash which is really bad because it's probably going to WSOD the app. 

Let's monitor this and see if it gets worse.

**Comment by ZhangYiJiang** [comment]
So far all of the reports except one has involved someone searching for MA modules. Could just be because MA modules are really popular? I couldn't reproduce it with any of the query the users used.
